[project]
name = "postman-export"
version = "0.1.0"
description = "Postman collections exporter with CLI and web interface"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "streamlit>=1.28.0",
]
